### ISSUE TITLE
Probabilistic semantics

### ISSUE THREAD

**Issue by christoph-grimm** [TUK-CPS/jAADD#3]
Probabilistic semantics via an own kind of symbol are a feature-wish. 
To come in version 3.0?

**Comment by breandan** [comment]
Hi Cristoph, what a nice library you've written! Just leaving a note to say I was looking at implementing sum-product networks using AADDs and would love to see this feature!

**Comment by christoph-grimm** [comment]
We will publish V3 very soon. If interested in testing let us know. 
V3 includes 
V3 of jAADD will be published soon that separates expressions from the pure computational library. 
- The expression language will be in a separate repository SysMD that adds support for
    + creating feature models and constraint networks in SysMLv2 inspired language, based on subset of its meta-model
    + bi-directional computations
    + support for real-valued quantities with SI and national units
    + support for integers, strings, booleans
    + consideration of FP roundoff errors

Howver, probabilistic semantics for nonlinear operations are patent pending and is excluded from V3 so far.
